package inventaris_aset;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import static javax.print.attribute.Size2DSyntax.MM;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
/**
 *
 * @author Windows 8.1
 */
public class run extends javax.swing.JFrame {
    
    public run() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        barang = new javax.swing.JMenuItem();
        jenis = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        bmasuk = new javax.swing.JMenuItem();
        bkeluar = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        lmasuk = new javax.swing.JMenuItem();
        lkeluar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFocusable(false);
        setMaximumSize(null);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Swis721 Hv BT", 0, 24)); // NOI18N
        jLabel4.setText("APLIKASI INVENTARIS GUDANG");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 13, 400, 80));

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Swis721 Hv BT", 0, 36)); // NOI18N
        jLabel5.setText("TELKOM AKSES");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(288, 73, 350, 40));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-50, -70, 200, 550));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventaris_aset/IMG-20230114-WA0051.jpg"))); // NOI18N
        jLabel1.setFocusable(false);
        jLabel1.setMaximumSize(null);
        jLabel1.setMinimumSize(null);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, -60, 760, 540));

        jMenu1.setText("MASTER");

        barang.setText("BARANG");
        barang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barangActionPerformed(evt);
            }
        });
        jMenu1.add(barang);

        jenis.setText("JENIS BARANG");
        jenis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jenisActionPerformed(evt);
            }
        });
        jMenu1.add(jenis);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("TRANSAKSI");

        bmasuk.setText("BARANG MASUK");
        bmasuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bmasukActionPerformed(evt);
            }
        });
        jMenu2.add(bmasuk);

        bkeluar.setText("BARANG KELUAR");
        bkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bkeluarActionPerformed(evt);
            }
        });
        jMenu2.add(bkeluar);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("LAPORAN");

        lmasuk.setText("LAPORAN BARANG MASUK");
        lmasuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lmasukActionPerformed(evt);
            }
        });
        jMenu3.add(lmasuk);

        lkeluar.setText("LAPORAN BARANG KELUAR");
        lkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lkeluarActionPerformed(evt);
            }
        });
        jMenu3.add(lkeluar);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void barangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barangActionPerformed
    new barang().setVisible(true);            // TODO add your handling code here:
    }//GEN-LAST:event_barangActionPerformed

    private void jenisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jenisActionPerformed
    new jenis().setVisible(true);         // TODO add your handling code here:
    }//GEN-LAST:event_jenisActionPerformed

    private void bmasukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bmasukActionPerformed
    new brg_terima().setVisible(true);         // TODO add your handling code here:
    }//GEN-LAST:event_bmasukActionPerformed

    private void bkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bkeluarActionPerformed
    new brg_keluar().setVisible(true);         // TODO add your handling code here:
    }//GEN-LAST:event_bkeluarActionPerformed

    private void lmasukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lmasukActionPerformed
    new config().tampilLaporan("src/Laporan/lmasuk.jrxml","SELECT * FROM terima_brg");        // TODO add your handling code here:
    }//GEN-LAST:event_lmasukActionPerformed

    private void lkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lkeluarActionPerformed
    new config().tampilLaporan("src/laporan/lkeluar.jrxml","SELECT * FROM keluar_brg");       // TODO add your handling code here:
    }//GEN-LAST:event_lkeluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new run().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem barang;
    private javax.swing.JMenuItem bkeluar;
    private javax.swing.JMenuItem bmasuk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem jenis;
    private javax.swing.JMenuItem lkeluar;
    private javax.swing.JMenuItem lmasuk;
    // End of variables declaration//GEN-END:variables
}
